'use client';
import './global.css';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

const metadata = {
  title: 'Welcome to Halliburton Assessment',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <header className="border-b bg-white shadow-md">
          <div className=" mx-auto px-6 py-4 flex items-center justify-between">
            <div className="text-2xl font-bold text-gray-800">
              <a href="/" className="text-red-700 hover:text-black transition">
                Halliburton Assessment
              </a>
            </div>

            <div className="flex">
              <nav className="flex items-center space-x-6">
                <a
                  href="/posts"
                  className={cn(
                    'text-sm font-medium text-gray-700',
                    'hover:text-blue-500 transition'
                  )}
                >
                  Posts
                </a>
                <a
                  href="/admin"
                  className={cn(
                    'text-sm font-medium text-gray-700',
                    'hover:text-blue-500 transition'
                  )}
                >
                  Dashboard
                </a>
              </nav>
              <Button
                variant="destructive"
                size="sm"
                className="mx-4"
                onClick={() => {
                  localStorage.removeItem('access_token');
                  window.location.href = '/auth';
                }}
              >
                Logout
              </Button>
            </div>
          </div>
        </header>

        <main className="px-6 py-6">{children}</main>
      </body>
    </html>
  );
}
